spring:
    application:
        name: registry-center

server:
    port: 8761 #启动端口

eureka:
  instance:
      hostname: localhost
      appname: registry-center
      statusPageUrlPath: ${management.context-path}/info
      healthCheckUrlPath: ${management.context-path}/health
  client:
      registerWithEureka: false  #false:不作为一个客户端注册到注册中心
      fetchRegistry: false      #为true时，可以启动，但报异常：Cannot execute request on any known server
logging:
  file: registry_center.log
  level: com.ywing.platform=DEBUG